### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by basketas** [franccesco/getaltname#8]
Installed it on Kali linux through PIP, but got this when I tried to run it
![image](https://user-images.githubusercontent.com/16399561/52924338-ae752080-332c-11e9-8e2b-f9cf6a45540c.png)

**Comment by franccesco** [comment]
Now that's weird, are you using the latest Python version? I'm going to check this when I get home today. Thank you for letting me know about this!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by basketas** [comment]
Yap, just installed the latest version, and also tried on both Windows and Linux

**Comment by franccesco** [comment]
Hello again! Sorry for the long wait, it seems that you're running a python version not supported by the tool. Currently you need to install Python 3.6 or greater to be able to run it. Also I have done some maintenance ask on the tool so remember to upgrade it using pip:
```
pip install --user --upgrade gsan
```
Make sure that you're running the latest Python version with:
```
python --version
```

Let me know if you still encounter this issue.
